global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: 
        - 192.168.240.4:9090

  - job_name: 'web-app'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 192.168.240.3:3001